-- Create Database
CREATE DATABASE IF NOT EXISTS study_group_matcher;
USE study_group_matcher;

--  Create Tables
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DepartmentId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Address TEXT
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
    ProfessorId INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    DepartmentId INT,
    FOREIGN KEY (DepartmentId) REFERENCES DEPARTMENT(DepartmentId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS COURSE (
    CourseID VARCHAR(20) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    DepartmentId INT,
    ProfessorId INT,
    FOREIGN KEY (DepartmentId) REFERENCES DEPARTMENT(DepartmentId) ON DELETE SET NULL,
    FOREIGN KEY (ProfessorId) REFERENCES PROFESSOR(ProfessorId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS STUDENT (
    StudentId INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    DepartmentId INT,
    FOREIGN KEY (DepartmentId) REFERENCES DEPARTMENT(DepartmentId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS STUDY_GROUP (
    GroupId INT AUTO_INCREMENT PRIMARY KEY,
    CourseId VARCHAR(20) NOT NULL,
    LeaderStudentId INT,
    GroupName VARCHAR(100),
    GroupType VARCHAR(50),
    Schedule JSON,
    ProfessorApproval BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (CourseId) REFERENCES COURSE(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (LeaderStudentId) REFERENCES STUDENT(StudentId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS REQUEST (
    StudentId INT,
    GroupId INT,
    Status ENUM('Pending', 'Accepted', 'Rejected') DEFAULT 'Pending',
    PRIMARY KEY (StudentId, GroupId),
    FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId) ON DELETE CASCADE,
    FOREIGN KEY (GroupId) REFERENCES STUDY_GROUP(GroupId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ENROLL (
    StudentId INT,
    CourseId VARCHAR(20),
    PRIMARY KEY (StudentId, CourseId),
    FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId) ON DELETE CASCADE,
    FOREIGN KEY (CourseId) REFERENCES COURSE(CourseID) ON DELETE CASCADE
);
